### ISSUE TITLE
Bug report - Transition in app menu (mobile browser)

### ISSUE THREAD

**Issue by hrdyjan1** [levinhtuyen/portfolio-developer-and-blog#1]
## Description:

When using the portfolio website on a mobile device, navigating to the "Blog" section via the mobile menu results in a 404 error. The URL /blog is not found, but the correct path appears to be /posts.

## Steps to Reproduce:

- Open the portfolio website on a mobile device (or use mobile view in a browser).
- Tap the menu icon to open the mobile navigation menu.
- Tap on the "Blog" menu item.
- Observe that the page redirects to /blog and displays a 404 error (Page Not Found).

## Expected Behavior:
The "Blog" menu item should redirect to /posts, which correctly displays the blog content.

**Comment by levinhtuyen** [comment]
Thank you for reporting, the issue has been resolved.
